//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DAL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class BD : global::System.Configuration.ApplicationSettingsBase {
        
        private static BD defaultInstance = ((BD)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BD())));
        
        public static BD Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALEPC;Initial Catalog=Renta;Integrated Security=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-9AC7BTS\\SQLEXPRESS;Initial Catalog=Renta;Integrated Security=" +
            "True")]
>>>>>>> parent of 003543e... Merge branch 'master' of https://github.com/valeria22ha/PickACar
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ALEPC;Initial Catalog=Renta;Integrated Security=True")]
>>>>>>> parent of 96e376a... A
        public string Conexion {
            get {
                return ((string)(this["Conexion"]));
            }
        }
    }
}
